# Generated by Django 5.1.7 on 2025-03-10 14:34

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('WHITE', 'White'), ('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('GOLD', 'Gold')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of this hole (optional)')),
                ('mens_par', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('mens_yards', models.IntegerField(validators=[django.core.validators.MaxValueValidator(600), django.core.validators.MinValueValidator(1)])),
                ('mens_index', models.IntegerField(validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(1)])),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holes', to='courses.course')),
            ],
            options={
                'unique_together': {('name', 'course'), ('number', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title this round (optional)')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tee_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teecolor', to='courses.teecolor')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tee_colors',
            field=models.ManyToManyField(related_name='courses', to='courses.teecolor'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strokes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('hole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.hole')),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.round')),
            ],
            options={
                'unique_together': {('round', 'hole')},
            },
        ),
        migrations.CreateModel(
            name='Tee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('WHITE', 'White'), ('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('GOLD', 'Gold')], max_length=255, null=True)),
                ('yards', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('hole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tees', to='courses.hole')),
            ],
            options={
                'unique_together': {('color', 'hole')},
            },
        ),
    ]
