# Generated by Django 5.1.7 on 2025-03-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('handicap_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wensum_handicap', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('valley_handicap', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
        ),
    ]
